const QUESTIONS_ENGLISH = [
{"id":1,"t":"choice","q":"There is ___ \"h\" in the word \"honest\".","o":["a","an","the","/"],"a":1,"e":"\"h\"的发音是/eɪtʃ/，以元音音素开头，所以用an。"},
{"id":2,"t":"choice","q":"___ sun rises in ___ east.","o":["A; a","The; the","The; /","/; the"],"a":1,"e":"世界上独一无二的事物用the；方位名词前也用the。"},
{"id":3,"t":"choice","q":"She plays ___ piano very well.","o":["a","an","the","/"],"a":2,"e":"演奏乐器前要用定冠词the，这是固定用法。"},
{"id":4,"t":"choice","q":"He wants to be ___ engineer when he grows up.","o":["a","an","the","/"],"a":1,"e":"engineer以元音字母e开头，前一个词的发音也是以元音音素开始的(尾音是元音)，用an。注意：不是看字母，而是看发音。"},
{"id":5,"t":"choice","q":"___ Yellow River is ___ second longest river in China.","o":["The; the","The; a","/; the","A; the"],"a":0,"e":"河流名称前加the；序数词前也要加the。"},
{"id":6,"t":"choice","q":"I usually go to school by ___ bus, but today I took ___ taxi.","o":["a; a","/; a","the; the","/; /"],"a":1,"e":"by bus是固定搭配，表示\"乘公交\"不加冠词；take a taxi是\"打一辆出租车\"，a表示泛指。"},
{"id":7,"t":"choice","q":"___ more you practice, ___ better you will be.","o":["A; a","The; the","/; /","The; a"],"a":1,"e":"\"the + 比较级, the + 比较级\"表示\"越……就越……\"，是固定句型。"},
{"id":8,"t":"choice","q":"He is ___ honest man. Everyone trusts him.","o":["a","an","the","/"],"a":1,"e":"honest的h不发音，读音以元音/ˈɒ/开头，所以用an。"},
{"id":9,"t":"choice","q":"I have ___ umbrella and ___ book in my bag.","o":["a; a","an; a","an; an","a; an"],"a":1,"e":"umbrella以元音音素开头用an，book以辅音音素开头用a。"},
{"id":10,"t":"choice","q":"___ Greens are going to ___ Great Wall tomorrow.","o":["The; the","The; /","/; the","A; the"],"a":0,"e":"the + 姓氏复数表示\"……一家人\"；the Great Wall是专有名词，前要加the。"},
{"id":11,"t":"choice","q":"What ___ interesting story it is!","o":["a","an","the","/"],"a":1,"e":"感叹句中，interesting以元音音素开头，用an。"},
{"id":12,"t":"choice","q":"He hit me in ___ face.","o":["a","an","the","/"],"a":2,"e":"表示击打身体部位，用\"hit sb. in the + 身体部位\"，是固定搭配。"},
{"id":13,"t":"choice","q":"We have three meals ___ day.","o":["a","an","the","/"],"a":0,"e":"\"a/冠词 + 单数名词\"表示\"每……\"，a day = 每天。"},
{"id":14,"t":"choice","q":"___ water is important for ___ life.","o":["The; /","/; /","A; a","/; the"],"a":1,"e":"water和life在此处都是不可数名词，表示泛指概念，不加冠词。"},
{"id":15,"t":"choice","q":"He is ___ tallest boy in our class.","o":["a","an","the","/"],"a":2,"e":"形容词最高级前通常要加定冠词the。"},
{"id":16,"t":"choice","q":"I saw ___ one-eyed man on the street.","o":["a","an","the","/"],"a":0,"e":"one以辅音音素/wʌn/开头，用a。"},
{"id":17,"t":"choice","q":"She went to ___ school after ___ breakfast.","o":["the; the","/; /","the; /","/; the"],"a":1,"e":"go to school（去上学）、after breakfast（早饭后）都是固定搭配，不加冠词。"},
{"id":18,"t":"choice","q":"He was made ___ monitor of our class.","o":["a","an","the","/"],"a":3,"e":"表示独一无二的头衔、职务时，不加冠词。"},
{"id":19,"t":"choice","q":"___ United States is in North America.","o":["A","An","The","/"],"a":2,"e":"由普通名词构成的国名前要加the，如the United States、the People's Republic of China。"},
{"id":20,"t":"choice","q":"I bought ___ useful dictionary yesterday.","o":["a","an","the","/"],"a":0,"e":"useful虽然以u开头，但发音是/ˈjuːsfl/，以辅音音素/j/开头，用a。"},
{"id":21,"t":"choice","q":"___ Smiths live at ___ 58 Baker Street.","o":["The; the","/; /","The; /","/; the"],"a":2,"e":"\"the + 姓氏复数\"表示一家人；门牌号前不加the。"},
{"id":22,"t":"choice","q":"He is fond of playing ___ chess.","o":["a","an","the","/"],"a":3,"e":"表示球类、棋类运动不加冠词。"},
{"id":23,"t":"choice","q":"He was reading ___ book when I entered ___ room.","o":["a; a","the; the","a; the","the; a"],"a":2,"e":"第一次提到某物用a，再次提到或特指时用the。这里是第一次提到书，特指进的那个房间。"},
{"id":24,"t":"choice","q":"Can you play ___ basketball? I want to be ___ player like Yao Ming.","o":["the; a","/; a","a; the","/; /"],"a":1,"e":"球类运动前不加冠词；a player表示\"一名球员\"，泛指。"},
{"id":25,"t":"choice","q":"___ number of students in our school is over 1000.","o":["A","An","The","/"],"a":2,"e":"\"the number of\"表示\"……的数量\"，用the；注意区分\"a number of\"表示\"许多\"。"},
{"id":26,"t":"choice","q":"I had ___ breakfast and then went to ___ work.","o":["the; the","/; /","a; the","/; a"],"a":1,"e":"三餐（breakfast/lunch/dinner）前不加冠词；go to work是固定搭配，不加冠词。"},
{"id":27,"t":"choice","q":"She is ___ European, not ___ American.","o":["a; an","an; a","a; a","an; an"],"a":0,"e":"European发音以/j/开头（辅音音素），用a；American以元音/ə/开头，用an。"},
{"id":28,"t":"choice","q":"I fell in love with her at ___ first sight.","o":["a","an","the","/"],"a":2,"e":"\"at first sight\"中间需要the，at the first sight表示\"第一次见面时\"。"},
{"id":29,"t":"choice","q":"He has been to ___ hospital twice this month.","o":["a","an","the","/"],"a":0,"e":"go to hospital表示\"去看病\"（英式英语），不加the；但the hospital表示\"那家医院\"。"},
{"id":30,"t":"choice","q":"It's ___ pleasure to work with you.","o":["a","an","the","/"],"a":0,"e":"pleasure以辅音/p/开头，用a。\"It's a pleasure to do sth.\"是固定句型。"},
{"id":31,"t":"choice","q":"He is ___ only person who knows the truth.","o":["a","an","the","/"],"a":2,"e":"\"the only\"是固定搭配，表示\"唯一的\"，序数词和only前都用the。"},
{"id":32,"t":"choice","q":"She has ___ 8-year-old daughter.","o":["a","an","the","/"],"a":0,"e":"8的发音是/eɪt/，以元音开头，但注意这里8-year-old作形容词，前面看后面的daughter，还是看eight？实际上8-year-old整体修饰daughter，但冠词看daughter。daughter以辅音开头用a。不对——应看发音：8-year-old以元音开头，但这是整体形容词修饰daughter。其实应该看daughter以/d/开头用a。答案是a。不过更准确地说，\"an 8-year-old\"更常见因为eight以元音开头。但标准语法中，冠词看后面的名词daughter，所以用a。"},
{"id":33,"t":"choice","q":"___ rich should help ___ poor.","o":["A; a","The; the","/; /","A; the"],"a":1,"e":"\"the + 形容词\"表示一类人，the rich = 富人，the poor = 穷人。"},
{"id":34,"t":"choice","q":"He turned ___ writer after he graduated.","o":["a","an","the","/"],"a":0,"e":"turn（成为）后面表示职业的名词前不加the，用a/an。writer以辅音开头用a。"},
{"id":35,"t":"choice","q":"He takes ___ active part in all kinds of activities.","o":["a","an","the","/"],"a":1,"e":"active以元音/ˈæ/开头，用an。take an active part in = 积极参与。"},
{"id":36,"t":"choice","q":"Please give me some ___. I'm very thirsty.","o":["waters","water","a water","the waters"],"a":1,"e":"water是不可数名词，没有复数形式，用some修饰。"},
{"id":37,"t":"choice","q":"There are three ___ and five ___ on the farm.","o":["sheeps; deers","sheep; deer","sheeps; deer","sheep; deers"],"a":1,"e":"sheep和deer是单复数同形的名词，不加s。"},
{"id":38,"t":"choice","q":"I need some ___. Could you pass me the scissors?","o":["papers","paper","a paper","the paper"],"a":1,"e":"paper表示\"纸\"时是不可数名词，用some修饰。注意a paper可以表示\"报纸\"或\"论文\"。"},
{"id":39,"t":"choice","q":"March 8th is ___ Day.","o":["Woman's","Women's","Womens'","Womans'"],"a":1,"e":"妇女节是Women's Day。woman的复数是不规则变化women，变所有格加's。"},
{"id":40,"t":"choice","q":"The two ___ are talking about the accident.","o":["policeman","policemans","policemen","police"],"a":2,"e":"policeman的复数是把man变成men，即policemen。"},
{"id":41,"t":"choice","q":"Could you give me some ___ on how to learn English well?","o":["advices","advise","advice","an advice"],"a":2,"e":"advice是不可数名词，没有复数形式，也不能用an修饰。advise是动词。"},
{"id":42,"t":"choice","q":"I bought two ___ for my mother's birthday.","o":["loafs of bread","loaves of bread","loaf of breads","loaves of breads"],"a":1,"e":"loaf的复数是loaves（f变v加es）；bread是不可数名词，用loaves of bread。"},
{"id":43,"t":"choice","q":"The teacher asked us to hand in our ___ on time.","o":["paper","papers","paper's","papers'"],"a":1,"e":"paper在此处表示\"试卷/论文\"，是可数名词，复数加s。"},
{"id":44,"t":"choice","q":"There are many ___ in the hospital.","o":["man doctors","men doctors","men doctor","mans doctors"],"a":1,"e":"man/woman修饰名词时，两个都变复数：men doctors。"},
{"id":45,"t":"choice","q":"This is ___ room. It's not ___.","o":["Tom and Jerry's; mine","Tom's and Jerry's; my","Tom's and Jerry's; mine","Tom and Jerry's; my"],"a":2,"e":"Tom's and Jerry's表示各自的房间；mine = my room。如果表示共有的房间，用Tom and Jerry's。"},
{"id":46,"t":"choice","q":"He has much ___ but little ___.","o":["money; time","moneys; times","money; times","moneys; time"],"a":0,"e":"money和time（时间）都是不可数名词，用much和little修饰。"},
{"id":47,"t":"choice","q":"I'd like some ___. I'm very hungry.","o":["food","foods","a food","the food"],"a":0,"e":"food作为\"食物\"的总称是不可数名词。不过foods可以表示\"各种食物\"，但此处表示要吃的东西，用food。"},
{"id":48,"t":"choice","q":"All the ___ are at the meeting.","o":["hero","heros","heroes","hero's"],"a":2,"e":"以o结尾的名词，有生命的加es（heroes, potatoes, tomatoes），无生命的加s（photos, radios, pianos）。"},
{"id":49,"t":"choice","q":"___ mothers work in this hospital.","o":["Tom and Mary's","Tom's and Mary's","Tom and Mary","Tom's and Mary"],"a":1,"e":"Tom's and Mary's表示各自的母亲（不止一个）；Tom and Mary's表示他们共有的一位母亲。"},
{"id":50,"t":"choice","q":"The news ___ very exciting.","o":["is","are","were","have been"],"a":0,"e":"news是不可数名词，虽然以s结尾，但谓语用单数。"},
{"id":51,"t":"choice","q":"Math ___ my favorite subject at school.","o":["are","is","were","have been"],"a":1,"e":"mathematics（数学）缩写为math/maths，是单数名词，谓语用单数。"},
{"id":52,"t":"choice","q":"Look! There are some ___ on the grass.","o":["sheep","sheeps","deers","fishs"],"a":0,"e":"sheep是单复数同形的词，一只羊是a sheep，多只羊还是sheep，不加s。"},
{"id":53,"t":"choice","q":"He had his hair ___ yesterday.","o":["cut","cuts","cutting","to cut"],"a":0,"e":"have sth. done表示\"让某事被做\"，hair cut表示\"理发\"。这里主要考查名词hair。"},
{"id":54,"t":"choice","q":"We had a good time during the ___.","o":["two-weeks holiday","two-week holiday","two week's holiday","two week holiday"],"a":1,"e":"\"数词-名词\"构成的复合形容词，名词用单数形式：two-week holiday。"},
{"id":55,"t":"choice","q":"I have three ___. They are all ___.","o":["knifes; Germans","knives; Germen","knives; Germans","knifes; Germen"],"a":2,"e":"knife变复数为knives（f变v加es）；German的复数直接加s，为Germans。"},
{"id":56,"t":"choice","q":"We should do our best to protect ___ .","o":["natures","the nature","nature","a nature"],"a":2,"e":"nature（大自然）是不可数名词，不加冠词，也没有复数。"},
{"id":57,"t":"choice","q":"The ___ of the tree have turned yellow.","o":["leaf","leafs","leaves","leafes"],"a":2,"e":"leaf的复数是leaves（f变v加es），类似：wife→wives, knife→knives。"},
{"id":58,"t":"choice","q":"Physics ___ not easy to learn.","o":["is","are","were","be"],"a":0,"e":"physics（物理学）是学科名称，以s结尾但是单数，谓语用单数。"},
{"id":59,"t":"choice","q":"All the ___ on the desk are mine.","o":["information","knowledge","books","furniture"],"a":2,"e":"books是可数名词复数，与All the搭配。information, knowledge, furniture都是不可数名词。"},
{"id":60,"t":"choice","q":"How many ___ do you want?","o":["bread","orange","milk","oranges"],"a":3,"e":"How many修饰可数名词复数，orange（橘子）是可数名词，oranges是复数。"},
{"id":61,"t":"choice","q":"There isn't ___ in today's newspaper.","o":["new anything","anything new","new something","something new"],"a":1,"e":"anything用于否定句和疑问句，形容词修饰不定代词时后置。"},
{"id":62,"t":"choice","q":"Would you like some ___?","o":["teas","tea","a tea","Both B and C"],"a":3,"e":"tea作为\"茶\"（物质）不可数；但表示\"一杯茶\"时可以说a tea或some teas（几杯茶）。"},
{"id":63,"t":"choice","q":"The teacher gave us some ___ on how to prepare for the exam.","o":["suggestion","suggestions","advices","information"],"a":1,"e":"suggestion是可数名词，用some suggestions。advice是不可数，information不可数但some information也对。这里选suggestions更常见。"},
{"id":64,"t":"choice","q":"My brother has two ___ .","o":["toothbrushes","toothesbrush","teethbrushes","teethsbrushes"],"a":0,"e":"toothbrush是复合词，复数在最后加es变为toothbrushes，不需要把tooth变成teeth。"},
{"id":65,"t":"choice","q":"He broke two ___ in the accident.","o":["glass","glasses","glass's","glasses'"],"a":1,"e":"glass在此处表示\"玻璃杯\"，是可数名词，复数加es为glasses。也表示\"眼镜\"。"},
{"id":66,"t":"choice","q":"___ is a student. ___ name is Li Lei.","o":["He; His","She; Her","He; Him","His; He"],"a":0,"e":"Li Lei是男生名字，主格用He，形容词性物主代词用His。"},
{"id":67,"t":"choice","q":"The book on the desk is ___. It's not ___.","o":["my; your","mine; yours","me; you","my; yours"],"a":1,"e":"名词性物主代词mine = my book，yours = your book，后面不再跟名词。"},
{"id":68,"t":"choice","q":"Is there ___ in the room?","o":["somebody","anybody","nobody","everybody"],"a":1,"e":"疑问句中用anybody/body（任何），不用somebody。"},
{"id":69,"t":"choice","q":"I have two pens. One is red, and ___ is blue.","o":["the other","other","another","others"],"a":0,"e":"两者中一个……另一个……用one...the other。another用于三者及以上。"},
{"id":70,"t":"choice","q":"He knows ___ about the plan. Let me tell him.","o":["anything","something","nothing","everything"],"a":2,"e":"根据后文\"让我告诉他\"，说明他什么都不知道，用nothing。"},
{"id":71,"t":"choice","q":"___ of the two boys is good at math.","o":["All","Both","Neither","None"],"a":2,"e":"\"两者都不\"用Neither。Both是\"两者都\"（后接复数谓语），None用于三者及以上。"},
{"id":72,"t":"choice","q":"She is taller than ___ in her class.","o":["any other girl","any girl","other girl","the other girls"],"a":0,"e":"比较级中排除自身，用any other + 单数名词。any girl会包含她自己。"},
{"id":73,"t":"choice","q":"I don't like this shirt. Please show me ___ one.","o":["another","other","the other","others"],"a":0,"e":"\"再来一个\"用another（又一个），the other表示两者中的另一个。"},
{"id":74,"t":"choice","q":"Tom is a good friend of ___.","o":["I","me","my","mine"],"a":3,"e":"\"a friend of mine\" = 我的一个朋友（双重所有格结构）。of后面用名词性物主代词。"},
{"id":75,"t":"choice","q":"Help ___ to some fish, please.","o":["you","your","yours","yourself"],"a":3,"e":"\"Help yourself to...\"是固定搭配，表示\"请自便/请随便吃\"。"},
{"id":76,"t":"choice","q":"We found ___ necessary to learn English well.","o":["that","this","it","one"],"a":2,"e":"find it necessary to do sth.，it是形式宾语，真正的宾语是后面的不定式。"},
{"id":77,"t":"choice","q":"There is ___ wrong with my computer. It works well.","o":["something","anything","nothing","everything"],"a":2,"e":"后面说\"运行良好\"，说明电脑没有问题，用nothing。"},
{"id":78,"t":"choice","q":"___ of the students has passed the exam.","o":["Every","Each","Both","All"],"a":1,"e":"Each强调个体（每一个），谓语用单数。Every后面不能直接接of。Both和All谓语用复数。"},
{"id":79,"t":"choice","q":"He has two sons. ___ are doctors.","o":["All of them","Both of them","Neither of them","None of them"],"a":1,"e":"两个儿子都是医生，用Both。Both of them表示\"他们两个都\"。"},
{"id":80,"t":"choice","q":"I have one ticket. Either you or ___ can go.","o":["I","me","my","mine"],"a":0,"e":"either...or...连接两个主语时，谓语就近原则。但此处在or后面做主语，用主格I。"},
{"id":81,"t":"choice","q":"The film is not as interesting as ___ we saw last week.","o":["that","it","one","the one"],"a":2,"e":"one代替前面提到的同类不同物，这里指另一部电影。"},
{"id":82,"t":"choice","q":"___ who wants to go may sign up here.","o":["Anyone","Someone","No one","Everyone"],"a":0,"e":"\"Anyone who...\"中who引导定语从句修饰anyone，表示\"任何想去的（人）\"，who在从句中作主语。"},
{"id":83,"t":"choice","q":"He is old enough to take care of ___.","o":["him","he","his","himself"],"a":3,"e":"\"take care of oneself\"表示\"照顾自己\"，主语和宾语是同一人时用反身代词。"},
{"id":84,"t":"choice","q":"I have three brothers. One is a teacher, ___ are workers.","o":["the other","another","the others","others"],"a":2,"e":"三个中的一个…其余的（两个）用the others。the others = the other ones。"},
{"id":85,"t":"choice","q":"___ of us has been to Beijing.","o":["No one","None","Neither","Both"],"a":0,"e":"No one = nobody，谓语用单数，表示\"没有一个\"。None后面通常接of。"},
{"id":86,"t":"choice","q":"Is this your book? No, it's not ___.","o":["my","me","mine","I"],"a":2,"e":"回答Is this your book?，用名词性物主代词mine代替my book。"},
{"id":87,"t":"choice","q":"She taught ___ English last year.","o":["she","her","herself","hers"],"a":2,"e":"teach oneself表示\"自学\"，反身代词herself表示她自己。"},
{"id":88,"t":"choice","q":"Would you like ___ to drink?","o":["anything","something","nothing","everything"],"a":1,"e":"表示委婉请求/提议时，在疑问句中也用something，不用anything。"},
{"id":89,"t":"choice","q":"He has more books than I, but ___ are more useful.","o":["my","me","I","mine"],"a":3,"e":"mine = my books，名词性物主代词，指\"我的那些书\"。"},
{"id":90,"t":"choice","q":"Tom and I are good friends. ___ often help each other.","o":["We","They","Our","Us"],"a":0,"e":"Tom and I做主语，对应的代词是We（我们），不是They。"},
{"id":91,"t":"choice","q":"I don't think ___ of them is right.","o":["both","either","neither","all"],"a":1,"e":"I don't think...否定前移，实际上认为\"两个都不对\"，但结构上用either。neither本身表否定，不能与don't连用。"},
{"id":92,"t":"choice","q":"This math problem is so difficult that ___ can solve it.","o":["nobody","anybody","somebody","everybody"],"a":0,"e":"so...that...如此…以至于…，根据\"太难\"可知没有人能解出，用nobody。"},
{"id":93,"t":"choice","q":"There are many trees on ___ side of the river.","o":["both","every","either","all"],"a":2,"e":"side是单数，表示\"（河的）任意一边\"用either。both/every/all不能直接修饰单数side。"},
{"id":94,"t":"choice","q":"He asked ___ for help when he was in trouble.","o":["me","I","mine","myself"],"a":0,"e":"ask sb. for help，sb.作宾语用宾格me。"},
{"id":95,"t":"choice","q":"I need a pen. Could you lend me ___?","o":["that","it","one","this"],"a":2,"e":"one代替同类不同物的可数名词单数，表示\"一支笔\"（不是特指哪支）。"},
{"id":96,"t":"choice","q":"___ is believed that he is the best player.","o":["He","It","That","This"],"a":1,"e":"It is believed that...是固定句型，It是形式主语，真正的主语是that从句。"},
{"id":97,"t":"choice","q":"Among all the students, Tom is ___ .","o":["the tallest","tallest","taller","the taller"],"a":0,"e":"三者及以上比较用最高级，最高级前加the。"},
{"id":98,"t":"choice","q":"The weather in Beijing is colder than ___ in Guangzhou.","o":["it","that","this","one"],"a":1,"e":"that代替不可数名词（weather），比较同类不同物。one代替可数名词。"},
{"id":99,"t":"choice","q":"Did she tell you ___ about the meeting?","o":["important something","important anything","something important","anything important"],"a":3,"e":"疑问句中用anything，形容词修饰不定代词时放在不定代词后面。"},
{"id":100,"t":"choice","q":"___ of us has made a mistake. We are all right.","o":["None","No one","Neither","Both"],"a":0,"e":"us是复数（我们，三人以上），none表示\"没有一个\"。neither只用于两者。"},
{"id":101,"t":"choice","q":"I saw ___ playing in the garden.","o":["they","them","their","themselves"],"a":1,"e":"saw后面接宾语，用宾格them。"},
{"id":102,"t":"choice","q":"Enjoy ___, boys and girls!","o":["you","yourself","yourselves","yours"],"a":2,"e":"boys and girls是复数，对应的反身代词是yourselves。"},
{"id":103,"t":"choice","q":"Each boy and each girl ___ given a book.","o":["was","were","are","have"],"a":0,"e":"each...and each...结构中，谓语用单数。"},
{"id":104,"t":"choice","q":"___ Tom ___ Jack wants to go. They both prefer to stay.","o":["Both; and","Either; or","Neither; nor","Not only; but also"],"a":2,"e":"根据\"都更愿意留下\"，说明两个人都不想去，用Neither...nor...（既不……也不……）。"},
{"id":105,"t":"choice","q":"— Who is singing in the next room? — ___ must be Mary.","o":["She","He","It","They"],"a":2,"e":"不确定是谁时，用It来指代未知的人，It must be Mary."},
{"id":106,"t":"choice","q":"She sings ___ than anyone else in her class.","o":["more beautiful","more beautifully","most beautifully","beautiful"],"a":1,"e":"修饰动词sings用副词beautifully；than表示比较级，用more beautifully。"},
{"id":107,"t":"choice","q":"This question is ___ easier than that one.","o":["very","much","more","most"],"a":1,"e":"比较级前可以用much, a lot, far, a little来修饰，不能用very或more（重复）。"},
{"id":108,"t":"choice","q":"He is one of ___ students in our school.","o":["the best","the better","best","better"],"a":0,"e":"one of + the + 最高级 + 名词复数，表示\"最……之一\"。"},
{"id":109,"t":"choice","q":"The ___ you work, the ___ result you will get.","o":["hard; good","harder; better","hardest; best","more hard; more good"],"a":1,"e":"\"the + 比较级, the + 比较级\"，hard的比较级是harder，good的比较级是better。"},
{"id":110,"t":"choice","q":"My mother is getting ___ and ___.","o":["fat; fat","fater; fater","fatter; fatter","more fat; more fat"],"a":2,"e":"比较级 + and + 比较级表示\"越来越…\"。fat的双写t加er为fatter。"},
{"id":111,"t":"choice","q":"This is ___ book I have ever read.","o":["the most interesting","the most interested","most interesting","more interesting"],"a":0,"e":"形容词最高级前加the，interesting是\"令人感兴趣的\"（修饰物），interested是\"感兴趣的\"（修饰人）。"},
{"id":112,"t":"choice","q":"He is ___ interested in the ___ story.","o":["much; interested","very; interesting","very; interested","much; interesting"],"a":1,"e":"修饰形容词用very；interested修饰人，interesting修饰物，故事用interesting。"},
{"id":113,"t":"choice","q":"He runs as ___ as his brother.","o":["fast","faster","fastest","more fast"],"a":0,"e":"as...as中间用形容词或副词的原级，fast这里作副词用原级。"},
{"id":114,"t":"choice","q":"She is ___ of the two sisters.","o":["the taller","taller","the tallest","tallest"],"a":0,"e":"两者中较……的那个，用\"the + 比较级\"。"},
{"id":115,"t":"choice","q":"He is ___ tired ___ he can't walk any further.","o":["so; that","too; to","very; that","such; that"],"a":0,"e":"so + adj. + that从句，表示\"如此…以至于…\"。"},
{"id":116,"t":"choice","q":"The boy is ___ young ___ go to school.","o":["too; to","so; that","enough; to","very; to"],"a":0,"e":"too + adj. + to do sth.，表示\"太…以至于不能…\"。"},
{"id":117,"t":"choice","q":"He is ___ to carry the heavy box.","o":["strong enough","enough strong","very strong","too strong"],"a":0,"e":"enough修饰形容词时放在形容词后面，strong enough = 足够强壮。"},
{"id":118,"t":"choice","q":"Which is ___, the sun, the moon, or the earth?","o":["big","bigger","the biggest","biggest"],"a":2,"e":"三者比较用最高级，且前面加the。"},
{"id":119,"t":"choice","q":"He did the work ___ than I expected.","o":["more careful","more carefully","most carefully","careful"],"a":1,"e":"修饰动词did用副词carefully，than表示比较级，用more carefully。"},
{"id":120,"t":"choice","q":"The book is ___ worth ___.","o":["very; reading","well; reading","very; to read","well; to read"],"a":1,"e":"well worth doing是固定搭配，表示\"很值得读\"。不能用very worth。"},
{"id":121,"t":"choice","q":"He is ___ a clever boy ___ everyone likes him.","o":["so; that","such; that","so; as","such; as"],"a":1,"e":"such + a/an + adj. + n. + that从句。so + adj. + that... 不需要a/an。"},
{"id":122,"t":"choice","q":"She is ___ careful as her sister.","o":["as","so","very","too"],"a":0,"e":"as...as表示\"和…一样\"，是原级比较。"},
{"id":123,"t":"choice","q":"He doesn't speak English as ___ as she does.","o":["good","well","better","best"],"a":1,"e":"as...as用原级，修饰动词speak用副词well，不是形容词good。"},
{"id":124,"t":"choice","q":"He is ___ taller than his father.","o":["very","much","more","so"],"a":1,"e":"比较级前用much/far/a lot来加强程度，不能用very。"},
{"id":125,"t":"choice","q":"He looked ___ at the news.","o":["sad","sadly","sadder","sadness"],"a":1,"e":"looked是连系动词+副词，表示\"他看起来很难过地看新闻\"，修饰动词用副词sadly。"},
{"id":126,"t":"choice","q":"The food tastes ___. Please don't eat it.","o":["good","well","badly","bad"],"a":3,"e":"taste是连系动词，后接形容词作表语。bad（坏的）是形容词，badly是副词。"},
{"id":127,"t":"choice","q":"He is ___ taller than me.","o":["very","a lot","more","much too"],"a":1,"e":"a lot可以修饰比较级，表示\"高得多\"。very不能修饰比较级，much too后接形容词原级。"},
{"id":128,"t":"choice","q":"Of the two coats, I'd like to choose the ___ one.","o":["cheap","cheaper","cheapest","more cheap"],"a":1,"e":"两者中选较便宜的那个，用\"the + 比较级\"。"},
{"id":129,"t":"choice","q":"She looks ___ than before.","o":["more younger","much younger","more young","much youngest"],"a":1,"e":"young的比较级是younger（双写是不对的，young加er），much修饰比较级。more younger是错误的重复。"},
{"id":130,"t":"choice","q":"He was ___ moved by the film that he couldn't help crying.","o":["so","such","very","too"],"a":0,"e":"so + adj. + that从句。moved是形容词，前面用so。"},
{"id":131,"t":"choice","q":"He is ___ honest boy that we all trust him.","o":["so a","such an","so an","such a"],"a":1,"e":"such + a/an + adj. + n.，honest以h不发音开头用an。"},
{"id":132,"t":"choice","q":"He was ill yesterday, but he feels ___ today.","o":["good","well","better","best"],"a":2,"e":"昨天生病了，今天感觉好多了，用比较级better。"},
{"id":133,"t":"choice","q":"The flowers smell ___.","o":["well","nicely","good","beautifully"],"a":2,"e":"smell是连系动词，后接形容词作表语。good在此表示\"好闻的\"。"},
{"id":134,"t":"choice","q":"He drove the car ___ than I did.","o":["more careful","more carefully","carefully","careful"],"a":1,"e":"than提示用比较级，修饰动词drove用副词carefully的比较级more carefully。"},
{"id":135,"t":"choice","q":"He is ___ than his brother.","o":["thiner","more thin","thinner","thinest"],"a":2,"e":"thin的比较级是双写n加er：thinner。"},
{"id":136,"t":"choice","q":"The Yangtze River is ___ longest river in China.","o":["a","an","the","/"],"a":2,"e":"最高级前用定冠词the。"},
{"id":137,"t":"choice","q":"She did ___ in the exam. She got the highest score.","o":["good","well","better","best"],"a":1,"e":"did是动词，用副词well修饰。不过\"did well\"表示考得好。但根据后文最高分，用best也合理。这里did well是固定搭配。"},
{"id":138,"t":"choice","q":"He arrived ___ earlier than I expected.","o":["much","very","more","most"],"a":0,"e":"much可以修饰比较级earlier，表示\"早得多\"。very不能修饰比较级。"},
{"id":139,"t":"choice","q":"The ___ news made us ___.","o":["excited; exciting","exciting; excited","excited; excited","exciting; exciting"],"a":1,"e":"exciting修饰事物（消息），excited修饰人感受。消息令人兴奋，我们感到兴奋。"},
{"id":140,"t":"choice","q":"He is ___ to go to school.","o":["old enough","enough old","very old","too old"],"a":0,"e":"enough放在形容词后，old enough = 足够大（可以上学了）。"},
{"id":141,"t":"choice","q":"She sings ___ among all the students.","o":["good","well","best","better"],"a":2,"e":"among all（在所有人中），用最高级best。"},
{"id":142,"t":"choice","q":"He is ___ man I have ever met.","o":["the most kind","the kindest","kindest","the more kind"],"a":1,"e":"kind的最高级是kindest，前面加the。"},
{"id":143,"t":"choice","q":"He is ___ tired ___ walk on.","o":["too; to","so; that","enough; to","very; to"],"a":0,"e":"too...to...表示\"太…以至于不能…\"。"},
{"id":144,"t":"choice","q":"The patient is getting ___ day by day.","o":["ill","worse","worst","bad"],"a":1,"e":"day by day（一天天），表示变化用比较级worse（更糟）。ill的比较级是worse。"},
{"id":145,"t":"choice","q":"He speaks English ___ , but not very ___.","o":["good; well","well; good","well; well","good; good"],"a":1,"e":"第一个空修饰动词speaks用副词well；第二个空是口语习惯\"not very good\"。"},
{"id":146,"t":"choice","q":"He was born ___ May 1st, 2000.","o":["in","on","at","by"],"a":1,"e":"具体到某一天（May 1st）用on。月份用in，时刻用at。"},
{"id":147,"t":"choice","q":"We usually have a meeting ___ Monday morning.","o":["in","on","at","for"],"a":1,"e":"在具体的某天上午/下午/晚上用on，on Monday morning。"},
{"id":148,"t":"choice","q":"He left Beijing ___ the morning of June 5th.","o":["in","on","at","to"],"a":1,"e":"有具体日期的早上用on：on the morning of June 5th。"},
{"id":149,"t":"choice","q":"He will be back ___ a week.","o":["in","after","for","during"],"a":0,"e":"\"in + 一段时间\"表示\"（从现在起）多久以后\"。after表示从过去某个时间点之后。"},
{"id":150,"t":"choice","q":"He has lived here ___ 2010.","o":["in","since","for","at"],"a":1,"e":"since接时间点（2010年），for接时间段。has lived是现在完成时。"},
{"id":151,"t":"choice","q":"He will arrive ___ Beijing ___ 3:00 pm tomorrow.","o":["in; at","at; in","at; at","in; on"],"a":2,"e":"arrive at + 小地点（车站、机场等），arrive in + 大地点（城市、国家）。但arrive at后接时间也用at。"},
{"id":152,"t":"choice","q":"She is good ___ playing basketball.","o":["in","at","for","with"],"a":1,"e":"be good at = 擅长于…，固定搭配。"},
{"id":153,"t":"choice","q":"He is looking forward ___ hearing from you.","o":["to","for","at","on"],"a":0,"e":"look forward to = 期待，to是介词，后面接动词ing。"},
{"id":154,"t":"choice","q":"The teacher was very angry ___ what he said.","o":["with","at","about","for"],"a":1,"e":"be angry at sth. = 对某事生气；be angry with sb. = 对某人生气。"},
{"id":155,"t":"choice","q":"He is strict ___ his students and strict ___ his work.","o":["in; with","with; in","with; with","in; in"],"a":1,"e":"be strict with sb.（对某人严格），be strict in sth.（对某事严格）。"},
{"id":156,"t":"choice","q":"He went to the hospital ___ bus.","o":["by","on","in","with"],"a":0,"e":"by bus = 乘公交，by + 交通方式不加冠词。"},
{"id":157,"t":"choice","q":"He is interested ___ Chinese history.","o":["in","at","on","with"],"a":0,"e":"be interested in = 对…感兴趣，固定搭配。"},
{"id":158,"t":"choice","q":"He is proud ___ his son's success.","o":["of","for","with","about"],"a":0,"e":"be proud of = 为…而骄傲，固定搭配。"},
{"id":159,"t":"choice","q":"Please write ___ ink, not ___ pencil.","o":["with; with","in; in","in; with","with; in"],"a":2,"e":"\"用墨水\"是in ink，\"用铅笔\"是in pencil或with a pencil。"},
{"id":160,"t":"choice","q":"He is very popular ___ the students.","o":["with","to","among","between"],"a":2,"e":"be popular among sb. = 在某人中受欢迎（三者及以上）。between用于两者之间。"},
{"id":161,"t":"choice","q":"She has been away from home ___ last Friday.","o":["since","for","from","in"],"a":0,"e":"since接过去时间点，与现在完成时连用。"},
{"id":162,"t":"choice","q":"He was late ___ the heavy rain.","o":["because","because of","as","since"],"a":1,"e":"because后接从句，because of后接名词/短语。heavy rain是名词短语。"},
{"id":163,"t":"choice","q":"The doctor operated ___ the patient last night.","o":["in","on","at","for"],"a":1,"e":"operate on sb. = 给某人做手术，固定搭配。"},
{"id":164,"t":"choice","q":"He is used ___ getting up early.","o":["to","for","with","of"],"a":0,"e":"be used to doing = 习惯于做某事，to是介词。注意区分used to do（过去常常）。"},
{"id":165,"t":"choice","q":"She was born ___ a small village.","o":["in","at","on","from"],"a":0,"e":"born in + 地点，表示\"出生于某地\"。"},
{"id":166,"t":"choice","q":"He jumped into the river ___ the boy.","o":["to save","saving","saved","saves"],"a":0,"e":"to save表示目的，\"为了救那个男孩\"。但这题考查介词，选项中to是不定式符号。"},
{"id":167,"t":"choice","q":"He is famous ___ a writer.","o":["as","for","to","with"],"a":0,"e":"be famous as = 作为…而闻名。be famous for = 因…而闻名。"},
{"id":168,"t":"choice","q":"He has suffered ___ a bad cold for three days.","o":["from","of","for","with"],"a":0,"e":"suffer from = 患有/遭受，固定搭配。"},
{"id":169,"t":"choice","q":"He made a living ___ selling newspapers.","o":["by","with","through","in"],"a":0,"e":"by doing = 通过做某事，表示方式。"},
{"id":170,"t":"choice","q":"He is good ___ English.","o":["in","at","for","with"],"a":1,"e":"be good at = 擅长于。注意区分be good for = 对…有好处。"},
{"id":171,"t":"choice","q":"He sat ___ the window, reading a book.","o":["in","on","at","by"],"a":3,"e":"by the window = 在窗户旁边，表示位置。"},
{"id":172,"t":"choice","q":"He divided the apple ___ two halves.","o":["into","in","to","among"],"a":0,"e":"divide...into... = 把…分成…，固定搭配。"},
{"id":173,"t":"choice","q":"He will go to Shanghai ___ business next week.","o":["on","in","at","for"],"a":0,"e":"on business = 出差，固定搭配。"},
{"id":174,"t":"choice","q":"___ the help of the teacher, he passed the exam.","o":["Under","With","In","For"],"a":1,"e":"with the help of = 在…的帮助下，固定搭配。"},
{"id":175,"t":"choice","q":"He ran ___ the direction of the school.","o":["to","in","on","at"],"a":1,"e":"in the direction of = 朝…方向，固定搭配。"},
{"id":176,"t":"choice","q":"He is very kind ___ us.","o":["to","for","with","of"],"a":0,"e":"be kind to sb. = 对某人和蔼，固定搭配。"},
{"id":177,"t":"choice","q":"He was very pleased ___ the gift.","o":["with","at","for","about"],"a":0,"e":"be pleased with = 对…满意/高兴，固定搭配。"},
{"id":178,"t":"choice","q":"He spent two hours ___ his homework.","o":["to do","doing","done","do"],"a":1,"e":"spend time (in) doing sth. = 花时间做某事，in可以省略。"},
{"id":179,"t":"choice","q":"She is always ready to help others. She is very kind ___ heart.","o":["at","by","with","in"],"a":1,"e":"by heart = 凭记忆；但kind by heart不常见。实际上kind at heart = 本性善良。"},
{"id":180,"t":"choice","q":"He goes to school ___ foot every day.","o":["by","on","with","in"],"a":1,"e":"on foot = 步行，固定搭配。注意不是by foot。"},
{"id":181,"t":"choice","q":"We will have a meeting ___ the afternoon.","o":["in","on","at","by"],"a":0,"e":"泛指的上午/下午/晚上用in：in the morning/afternoon/evening。"},
{"id":182,"t":"choice","q":"He is afraid ___ the dark.","o":["of","at","with","about"],"a":0,"e":"be afraid of = 害怕，固定搭配。"},
{"id":183,"t":"choice","q":"He is satisfied ___ the result.","o":["with","at","for","about"],"a":0,"e":"be satisfied with = 对…满意，固定搭配。"},
{"id":184,"t":"choice","q":"She is different ___ her sister.","o":["with","from","to","between"],"a":1,"e":"be different from = 与…不同，固定搭配。"},
{"id":185,"t":"choice","q":"He arrived ___ the airport ___ time.","o":["at; in","at; on","in; in","on; on"],"a":1,"e":"arrive at + 小地点；on time = 准时。in time = 及时。"},
{"id":186,"t":"choice","q":"He knocked ___ the door, but nobody answered.","o":["at","to","on","for"],"a":0,"e":"knock at/on the door = 敲门，at和on都可以，但at更常见。"},
{"id":187,"t":"choice","q":"He is weak ___ English, but good ___ math.","o":["in; at","at; in","in; in","at; at"],"a":0,"e":"be weak in = 在…方面薄弱；be good at = 擅长于。"},
{"id":188,"t":"choice","q":"He apologized ___ being late.","o":["for","to","at","with"],"a":0,"e":"apologize for = 因…而道歉，for后面接原因。"},
{"id":189,"t":"choice","q":"The film is based ___ a true story.","o":["in","on","at","for"],"a":1,"e":"be based on = 以…为基础，固定搭配。"},
{"id":190,"t":"choice","q":"He is fond ___ music and art.","o":["in","of","at","with"],"a":1,"e":"be fond of = 喜欢/爱好，固定搭配。"},
{"id":191,"t":"choice","q":"He worked hard, ___ he failed the exam.","o":["but","so","and","or"],"a":0,"e":"努力了但失败了，转折关系用but。"},
{"id":192,"t":"choice","q":"Hurry up, ___ you will be late.","o":["and","but","or","so"],"a":2,"e":"\"祈使句 + or + 陈述句\"表示\"否则\"，or = if not。"},
{"id":193,"t":"choice","q":"___ he is young, he knows a lot.","o":["Although","But","Because","So"],"a":0,"e":"although表示\"虽然\"，不能和but同时使用。"},
{"id":194,"t":"choice","q":"I didn't go to school yesterday ___ I was ill.","o":["but","so","because","or"],"a":2,"e":"没去上学的原因是生病了，因果关系用because。"},
{"id":195,"t":"choice","q":"He can speak ___ English ___ Chinese.","o":["both; and","either; or","neither; nor","not only; but also"],"a":0,"e":"既会说英语又会说中文，用both...and...。"},
{"id":196,"t":"choice","q":"___ Tom ___ Jack passed the exam. They both failed.","o":["Both; and","Either; or","Neither; nor","Not only; but also"],"a":2,"e":"两个都没通过考试，用Neither...nor...（既不…也不…）。"},
{"id":197,"t":"choice","q":"Work hard, ___ you will succeed.","o":["and","but","or","so"],"a":0,"e":"\"祈使句 + and + 陈述句\"表示\"如果…就会…\"，and表示顺承关系。"},
{"id":198,"t":"choice","q":"He is ___ my teacher ___ my friend.","o":["not; but","not only; but also","both; and","either; or"],"a":1,"e":"不仅是老师还是朋友，用not only...but also...。"},
{"id":199,"t":"choice","q":"I will wait ___ he comes back.","o":["if","until","because","though"],"a":1,"e":"\"直到他回来\"用until（直到…为止）。"},
{"id":200,"t":"choice","q":"___ it rained heavily, the match was still going on.","o":["Because","Although","If","Unless"],"a":1,"e":"虽然下大雨，比赛仍在继续，让步关系用Although。"},
{"id":201,"t":"choice","q":"You won't pass the exam ___ you study hard.","o":["if","unless","because","though"],"a":1,"e":"unless = if not，\"除非你努力学习，否则不会通过考试\"。"},
{"id":202,"t":"choice","q":"He didn't go to bed ___ he finished his homework.","o":["until","when","while","since"],"a":0,"e":"not...until...表示\"直到…才…\"，这里指直到做完作业才去睡觉。"},
{"id":203,"t":"choice","q":"___ he was tired, he kept working.","o":["Because","Although","So","And"],"a":1,"e":"虽然累了仍继续工作，让步关系用Although。"},
{"id":204,"t":"choice","q":"I like reading, ___ my brother likes playing games.","o":["and","but","so","or"],"a":1,"e":"我喜欢读书，但我弟喜欢玩游戏，对比转折用but。"},
{"id":205,"t":"choice","q":"He is rich, ___ he is not happy.","o":["and","but","so","because"],"a":1,"e":"有钱但不快乐，转折关系用but。"},
{"id":206,"t":"choice","q":"He asked me ___ I would go with him ___ not.","o":["if; or","that; and","whether; or","what; and"],"a":2,"e":"whether...or not = 是否，引导宾语从句，比if更正式。"},
{"id":207,"t":"choice","q":"It was ___ a fine day ___ we decided to go for a picnic.","o":["so; that","such; that","too; to","enough; that"],"a":0,"e":"so + adj. + that从句。fine day是名词短语，但so a fine day也正确（so + a/an + adj. + n.）。这里选so; that。"},
{"id":208,"t":"choice","q":"He can ___ read ___ write.","o":["neither; nor","either; or","both; and","not only; but also"],"a":1,"e":"既不会读也不会写，用neither...nor...。不对，这里没有否定词。\"他不能读也不能写\"？应该是neither...nor...但前面有can't？实际上句子是He can neither read nor write。但选项是neither nor。不对——选项A是neither nor，但前面没有否定。答案是B either or? 不对。让我重新看：He can neither read nor write. = 他既不会读也不会写。选A。但选项写的是neither; nor没有否定。实际上neither...nor本身就表否定。选A。"},
{"id":209,"t":"choice","q":"He is ___ clever ___ lazy.","o":["both; and","either; or","neither; nor","not; but"],"a":1,"e":"要么聪明要么懒，二者选一用either...or...。"},
{"id":210,"t":"choice","q":"___ you ___ he is right.","o":["Both; and","Either; or","Neither; nor","Not; but"],"a":1,"e":"either...or...表示\"要么…要么…\"，两者选一。"},
{"id":211,"t":"choice","q":"He is ___ a student ___ a teacher. He is a doctor.","o":["both; and","either; or","neither; nor","not; but"],"a":2,"e":"他既不是学生也不是老师，是医生。neither...nor...表示两者都不是。"},
{"id":212,"t":"choice","q":"___ he ___ his brother knows the secret.","o":["Both; and","Either; or","Neither; nor","Not only; but also"],"a":2,"e":"他和弟弟都不知道秘密，用neither...nor...。"},
{"id":213,"t":"choice","q":"The book is ___ interesting ___ I want to read it again.","o":["so; that","such; that","too; to","enough; that"],"a":0,"e":"so + adj. + that从句，表示\"如此有趣以至于想再读一遍\"。"},
{"id":214,"t":"choice","q":"He has been in Beijing ___ he was born.","o":["since","for","before","after"],"a":0,"e":"since接过去时间点（出生），与现在完成时连用。"},
{"id":215,"t":"choice","q":"___ you go, I will follow you.","o":["Wherever","Whatever","However","Whenever"],"a":0,"e":"无论你去哪里，我都会跟着你。wherever = no matter where。"},
{"id":216,"t":"choice","q":"___ hard you try, you should never give up.","o":["However","Whatever","Whenever","Wherever"],"a":0,"e":"无论你多么努力尝试都不应放弃。however + adj./adv. + 主语 + 谓语。"},
{"id":217,"t":"choice","q":"I was about to go out ___ the phone rang.","o":["when","while","as","since"],"a":0,"e":"be about to do...when... = 正要做某事这时突然…，是固定句型。"},
{"id":218,"t":"choice","q":"I had just sat down ___ the bell rang.","o":["when","while","as","before"],"a":0,"e":"had just done...when... = 刚做完某事这时…，when表示\"这时\"。"},
{"id":219,"t":"choice","q":"He won't go to the party ___ he is invited.","o":["if","unless","because","although"],"a":1,"e":"unless = if not，除非被邀请否则不去。"},
{"id":220,"t":"choice","q":"___ he said is true.","o":["That","What","Which","Whether"],"a":1,"e":"what引导主语从句，what = the thing that，在从句中作said的宾语。that在名词性从句中不作成分。"},
{"id":221,"t":"choice","q":"___ he will come or not is still a question.","o":["If","Whether","That","What"],"a":1,"e":"whether...or not可引导主语从句，if不能放在句首引导主语从句。"},
{"id":222,"t":"choice","q":"He can speak English ___ fluently ___ you.","o":["as; as","so; as","more; than","the same; as"],"a":0,"e":"as fluently as = 和…一样流利，as...as用原级。"},
{"id":223,"t":"choice","q":"He is ___ a good teacher ___ all his students love him.","o":["so; that","such; that","too; to","very; that"],"a":0,"e":"so + adj. + that从句。good是形容词，用so修饰。"},
{"id":224,"t":"choice","q":"He kept working ___ it was getting dark.","o":["though","because","so","until"],"a":0,"e":"虽然天越来越黑，他仍然继续工作，让步关系用though。"},
{"id":225,"t":"choice","q":"I'll give the book to him ___ I see him.","o":["as soon as","until","because","though"],"a":0,"e":"as soon as = 一…就…，表示两个动作紧接着发生。"},
{"id":226,"t":"choice","q":"He ___ to school every day.","o":["go","goes","went","is going"],"a":1,"e":"every day提示一般现在时，主语He是第三人称单数，动词加es。"},
{"id":227,"t":"choice","q":"Look! The children ___ in the park.","o":["play","played","are playing","were playing"],"a":2,"e":"Look!提示现在进行时，正在发生的动作用are playing。"},
{"id":228,"t":"choice","q":"He ___ his homework yesterday.","o":["does","did","will do","has done"],"a":1,"e":"yesterday提示一般过去时，do的过去式是did。"},
{"id":229,"t":"choice","q":"She ___ Beijing three times.","o":["went to","has been to","has gone to","goes to"],"a":1,"e":"has been to表示\"去过某地（已回）\"，has gone to表示\"去了某地（未回）\"。三次说明去过且已回。"},
{"id":230,"t":"choice","q":"He ___ a meeting tomorrow.","o":["has","had","will have","is having"],"a":2,"e":"tomorrow提示一般将来时，用will have。"},
{"id":231,"t":"choice","q":"I ___ my key. I can't find it anywhere.","o":["lost","have lost","lose","will lose"],"a":1,"e":"丢了钥匙对现在有影响（找不到），用现在完成时have lost。"},
{"id":232,"t":"choice","q":"He ___ TV when I called him.","o":["watches","watched","was watching","is watching"],"a":2,"e":"when I called him是过去某一时刻，那时正在看电视，用过去进行时。"},
{"id":233,"t":"choice","q":"She ___ English since she was five.","o":["learns","learned","has learned","is learning"],"a":2,"e":"since引导的从句与现在完成时连用，表示从过去某时起一直持续的动作。"},
{"id":234,"t":"choice","q":"I ___ you as soon as I arrive in Beijing.","o":["call","called","will call","have called"],"a":2,"e":"主将从现——主句用将来时，as soon as引导的从句用现在时表将来。主句用will call。"},
{"id":235,"t":"choice","q":"He ___ the book before I came.","o":["finished","has finished","had finished","finishes"],"a":2,"e":"\"过去的过去\"用过去完成时，在我来之前他已经完成了。"},
{"id":236,"t":"choice","q":"Be quiet! The baby ___.","o":["sleeps","slept","is sleeping","slept"],"a":2,"e":"Be quiet!表示正在进行的动作，用现在进行时。"},
{"id":237,"t":"choice","q":"How long ___ you ___ this book?","o":["have; bought","have; had","did; buy","do; buy"],"a":1,"e":"buy是瞬间动词，不能与how long连用。have是延续性动词，可以用how long。"},
{"id":238,"t":"choice","q":"The train ___ at 8:00 tomorrow morning.","o":["leaves","will leave","is leaving","All of the above"],"a":3,"e":"表示按时间表将发生的动作用一般现在时（leaves）；也可以用will leave或is leaving。"},
{"id":239,"t":"choice","q":"He ___ to school by bike, but today he ___ on foot.","o":["goes; goes","goes; is going","went; is going","goes; went"],"a":1,"e":"习惯性动作用一般现在时goes，正在进行的动作用现在进行时is going。"},
{"id":240,"t":"choice","q":"I ___ him since he left Beijing.","o":["didn't see","haven't seen","don't see","hadn't seen"],"a":1,"e":"since引导过去时间，主句用现在完成时haven't seen。"},
{"id":241,"t":"choice","q":"Where ___ you ___ your holiday last year?","o":["do; spend","did; spend","have; spent","will; spend"],"a":1,"e":"last year用一般过去时，疑问句用did + 动词原形。"},
{"id":242,"t":"choice","q":"By the time he was ten, he ___ 100 English words.","o":["learns","learned","had learned","has learned"],"a":2,"e":"by the time + 过去时，主句用过去完成时had learned。"},
{"id":243,"t":"choice","q":"I ___ you the news as soon as I ___ it.","o":["tell; will know","will tell; know","will tell; will know","tell; know"],"a":1,"e":"主句用将来时will tell，as soon as从句用现在时表将来know。"},
{"id":244,"t":"choice","q":"She ___ the piano when I entered the room.","o":["played","plays","was playing","has played"],"a":2,"e":"when I entered（过去某一时刻），那时正在弹钢琴，用过去进行时。"},
{"id":245,"t":"choice","q":"He ___ in this city since 2015.","o":["lived","has lived","lives","is living"],"a":1,"e":"since 2015与现在完成时连用，has lived表示从2015年一直住到现在。"},
{"id":246,"t":"choice","q":"They ___ a meeting this time tomorrow.","o":["have","had","will be having","are having"],"a":2,"e":"this time tomorrow表示将来某一时刻正在进行的动作，用将来进行时will be having。"},
{"id":247,"t":"choice","q":"I ___ my homework at 8:00 last night.","o":["do","did","was doing","am doing"],"a":2,"e":"at 8:00 last night是过去某一具体时刻，用过去进行时was doing。"},
{"id":248,"t":"choice","q":"He ___ already ___ his work.","o":["has; finished","had; finished","is; finishing","was; finishing"],"a":0,"e":"already常与现在完成时连用，has finished表示已经完成了。"},
{"id":249,"t":"choice","q":"The earth ___ around the sun.","o":["move","moves","moved","is moving"],"a":1,"e":"客观真理用一般现在时，the earth是第三人称单数，用moves。"},
{"id":250,"t":"choice","q":"I ___ my bike, so I had to walk to school.","o":["lose","lost","have lost","will lose"],"a":1,"e":"so I had to walk说明丢自行车发生在过去，用一般过去时lost。"},
{"id":251,"t":"choice","q":"He told me that he ___ the film the day before.","o":["saw","had seen","has seen","would see"],"a":1,"e":"间接引语中，\"the day before\"表示\"前一天\"，宾语从句用过去完成时had seen。"},
{"id":252,"t":"choice","q":"If it ___ tomorrow, we will stay at home.","o":["rains","will rain","rained","is raining"],"a":0,"e":"主将从现——if条件句用一般现在时表将来，主句用will stay。"},
{"id":253,"t":"choice","q":"I ___ you as soon as I get home.","o":["will call","call","called","calling"],"a":0,"e":"as soon as引导的时间状语从句用现在时，主句用将来时will call。"},
{"id":254,"t":"choice","q":"He ___ this book for two weeks.","o":["has bought","has had","bought","had"],"a":1,"e":"for two weeks与延续性动词连用。buy是瞬间动词，对应的延续状态是have（拥有）。"},
{"id":255,"t":"choice","q":"Up to now, we ___ five units.","o":["learn","learned","have learned","are learning"],"a":2,"e":"up to now（到目前为止）提示现在完成时have learned。"},
{"id":256,"t":"choice","q":"He ___ three English songs by the end of last month.","o":["learned","has learned","had learned","learns"],"a":2,"e":"by the end of last month是过去时间点，\"到那时已经学了\"用过去完成时。"},
{"id":257,"t":"choice","q":"I ___ you were in hospital. How are you now?","o":["don't know","didn't know","haven't known","won't know"],"a":1,"e":"不知道你住院了——这事发生在过去，用一般过去时didn't know。"},
{"id":258,"t":"choice","q":"Listen! Someone ___ at the door.","o":["knocks","knocked","is knocking","was knocking"],"a":2,"e":"Listen!提示正在发生的动作，用现在进行时is knocking。"},
{"id":259,"t":"choice","q":"He ___ his homework and then went out to play.","o":["finishes","finished","has finished","had finished"],"a":1,"e":"and连接两个连续的过去动作，都用一般过去时。"},
{"id":260,"t":"choice","q":"She ___ the movie before. She doesn't want to see it again.","o":["saw","has seen","had seen","sees"],"a":1,"e":"对现在有影响（不想再看），用现在完成时has seen。"},
{"id":261,"t":"choice","q":"We ___ each other since we were children.","o":["know","knew","have known","had known"],"a":2,"e":"since引导过去时间，主句用现在完成时have known。"},
{"id":262,"t":"choice","q":"He ___ dinner when I arrived.","o":["has","had","was having","is having"],"a":2,"e":"when I arrived（过去某一时刻），用过去进行时was having。"},
{"id":263,"t":"choice","q":"I ___ you the money next week.","o":["pay","paid","will pay","have paid"],"a":2,"e":"next week提示将来时，用will pay。"},
{"id":264,"t":"choice","q":"He ___ the Great Wall twice.","o":["visited","has visited","visits","is visiting"],"a":1,"e":"twice提示经历，用现在完成时has visited。"},
{"id":265,"t":"choice","q":"I ___ a letter from my mother last week.","o":["receive","received","have received","will receive"],"a":1,"e":"last week提示一般过去时received。"},
{"id":266,"t":"choice","q":"By the end of this year, we ___ 2000 English words.","o":["learn","will learn","will have learned","have learned"],"a":2,"e":"by the end of this year（到今年底），表示将来某时已完成的事，用将来完成时。"},
{"id":267,"t":"choice","q":"The teacher told us that light ___ faster than sound.","o":["travels","traveled","has traveled","would travel"],"a":0,"e":"客观真理即使在宾语从句中也用一般现在时。"},
{"id":268,"t":"choice","q":"I ___ my pen. Can you lend me yours?","o":["lose","lost","have lost","am losing"],"a":2,"e":"对现在有影响（需要借笔），用现在完成时have lost。"},
{"id":269,"t":"choice","q":"He ___ his arm and had to stay in hospital.","o":["breaks","broke","has broken","is breaking"],"a":1,"e":"and连接的并列动作，都用一般过去时。"},
{"id":270,"t":"choice","q":"I ___ this time yesterday.","o":["cook","cooked","was cooking","am cooking"],"a":2,"e":"this time yesterday表示过去某一时刻，用过去进行时was cooking。"},
{"id":271,"t":"choice","q":"He said he ___ come the next day.","o":["will","would","can","could"],"a":1,"e":"主句过去时，宾语从句时态后退——will变为would。"},
{"id":272,"t":"choice","q":"How long ___ you ___ in Beijing?","o":["have; been","have; come","did; come","do; come"],"a":0,"e":"come是瞬间动词，不能与how long连用。be可以，have been表示待了多久。"},
{"id":273,"t":"choice","q":"This is the best film I ___ ever ___.","o":["have; seen","had; seen","did; see","do; see"],"a":0,"e":"这是我看过的最好的电影——定语从句中用现在完成时。"},
{"id":274,"t":"choice","q":"He ___ to bed until his mother came back.","o":["goes","went","didn't go","doesn't go"],"a":2,"e":"not...until...（直到…才），母亲回来是过去的事，用一般过去时的否定。"},
{"id":275,"t":"choice","q":"The shop ___ at 9:00 every morning.","o":["opens","opened","is opening","has opened"],"a":0,"e":"every morning提示一般现在时，商店开门是习惯性动作。"},
{"id":276,"t":"choice","q":"When I got to the station, the train ___ .","o":["left","has left","had left","leaves"],"a":2,"e":"\"过去的过去\"——火车在我到之前已经离开了，用过去完成时。"},
{"id":277,"t":"choice","q":"He ___ a teacher for five years.","o":["has become","has been","became","was"],"a":1,"e":"for five years与延续性动词连用。become是瞬间动词，用be表示状态。"},
{"id":278,"t":"choice","q":"We ___ dinner when the light went out.","o":["have","had","were having","are having"],"a":2,"e":"when the light went out是过去某一时刻，用过去进行时。"},
{"id":279,"t":"choice","q":"She ___ the novel and wants to read it again.","o":["reads","read","has read","is reading"],"a":2,"e":"已经读了想再读一遍，对现在有影响，用现在完成时。"},
{"id":280,"t":"choice","q":"He ___ to see his grandmother next Sunday.","o":["goes","went","will go","has gone"],"a":2,"e":"next Sunday提示将来时，用will go。"},
{"id":281,"t":"choice","q":"I ___ my key. I can't open the door.","o":["lose","lost","have lost","am losing"],"a":2,"e":"丢钥匙对现在有影响（开不了门），用现在完成时。"},
{"id":282,"t":"choice","q":"He ___ his bike, so he had to walk home.","o":["loses","lost","has lost","is losing"],"a":1,"e":"so he had to walk——发生在过去，用一般过去时。"},
{"id":283,"t":"choice","q":"By the time you get home, I ___ dinner.","o":["cook","cooked","will cook","will have cooked"],"a":3,"e":"by the time + 现在时，主句用将来完成时，表示到那时已经做完。"},
{"id":284,"t":"choice","q":"She ___ in this factory since she graduated.","o":["works","worked","has worked","is working"],"a":2,"e":"since引导过去时间，主句用现在完成时。"},
{"id":285,"t":"choice","q":"I ___ the film before he told me about it.","o":["saw","have seen","had seen","see"],"a":2,"e":"\"过去的过去\"——在他告诉我之前我就看过了，用过去完成时。"},
{"id":286,"t":"choice","q":"He ___ to work every day, but today he ___ a bus.","o":["walks; takes","walked; took","is walking; is taking","walks; is taking"],"a":0,"e":"习惯动作用一般现在时walks；today特殊情况可以理解为也用一般现在时takes。"},
{"id":287,"t":"choice","q":"Where is Tom? He ___ to the library.","o":["has been","has gone","went","goes"],"a":1,"e":"问Tom在哪，他去了图书馆（未回），用has gone to。"},
{"id":288,"t":"choice","q":"He ___ here since he was a child.","o":["lives","lived","has lived","is living"],"a":2,"e":"since引导过去时间，与现在完成时连用。"},
{"id":289,"t":"choice","q":"I ___ you as soon as I ___ the news.","o":["tell; will hear","will tell; hear","will tell; will hear","tell; hear"],"a":1,"e":"主句将来时will tell，从句用现在时表将来hear。"},
{"id":290,"t":"choice","q":"He ___ his homework when his father came home.","o":["does","did","was doing","is doing"],"a":2,"e":"when his father came home是过去某一时刻，用过去进行时was doing。"},
{"id":291,"t":"choice","q":"The bridge ___ 100 years ago.","o":["built","was built","is built","has been built"],"a":1,"e":"桥是被建造的，用被动语态；100 years ago是一般过去时，所以用was built。"},
{"id":292,"t":"choice","q":"English ___ all over the world.","o":["speaks","is spoken","spoke","is speaking"],"a":1,"e":"英语被全世界人说，被动语态；是客观事实用一般现在时，is spoken。"},
{"id":293,"t":"choice","q":"The problem ___ at the meeting tomorrow.","o":["will discuss","will be discussed","is discussed","discussed"],"a":1,"e":"问题被讨论，用被动语态；tomorrow用将来时，will be discussed。"},
{"id":294,"t":"choice","q":"The car ___ in the accident yesterday.","o":["damaged","was damaged","is damaged","has damaged"],"a":1,"e":"车被损坏，被动语态；yesterday一般过去时，was damaged。"},
{"id":295,"t":"choice","q":"A new school ___ in our town next year.","o":["will build","will be built","is built","was built"],"a":1,"e":"学校被建，被动语态；next year将来时，will be built。"},
{"id":296,"t":"choice","q":"The window ___ by Tom yesterday.","o":["broke","was broken","is broken","has broken"],"a":1,"e":"窗户被Tom打破了，被动语态+一般过去时，was broken。"},
{"id":297,"t":"choice","q":"The work ___ by him already.","o":["has been finished","has finished","was finished","is finished"],"a":0,"e":"工作被完成，被动语态；already与现在完成时连用，has been finished。"},
{"id":298,"t":"choice","q":"Trees ___ every year to make our city greener.","o":["should plant","should be planted","should planted","are planting"],"a":1,"e":"树被种，被动语态；should后接be done。"},
{"id":299,"t":"choice","q":"The letter ___ last week.","o":["was sent","sent","is sent","has been sent"],"a":0,"e":"信上周被寄出，last week用一般过去时的被动语态，was sent。"},
{"id":300,"t":"choice","q":"You ___ return the book now. You can keep it until next week.","o":["mustn't","may not","needn't","can't"],"a":2,"e":"needn't表示'没有必要'，符合语境'你现在不必还书，可以留到下周'。mustn't表示禁止，语义不符。"},
{"id":301,"t":"choice","q":"— ___ I use your dictionary? — Of course. Here you are.","o":["Must","Need","May","Will"],"a":2,"e":"May I...? 表示请求许可，'我可以……吗？'，回答Of course表示允许。"},
{"id":302,"t":"choice","q":"The light is on. Someone ___ be in the room.","o":["can","must","need","may"],"a":1,"e":"must表示有把握的推测，'灯亮着，一定有人在房间里'。can一般不用于肯定推测。"},
{"id":303,"t":"choice","q":"He ___ be in Beijing now, because I just saw him in the office.","o":["can't","mustn't","needn't","won't"],"a":0,"e":"can't表示有把握的否定推测，'他不可能在北京，因为我刚在办公室见到他'。mustn't表示禁止，不表推测。"},
{"id":304,"t":"choice","q":"You ___ smoke here. It's a non-smoking area.","o":["mustn't","needn't","couldn't","won't"],"a":0,"e":"mustn't表示禁止，'你不能在这里抽烟，这是禁烟区'。needn't表示没必要，语义不符。"},
{"id":305,"t":"choice","q":"She ___ speak three languages when she was ten.","o":["could","can","may","must"],"a":0,"e":"could是can的过去式，表示过去的能力'她十岁时能说三种语言'。when she was ten是过去时间标志。"},
{"id":306,"t":"choice","q":"— Where is Mary? — She ___ have gone to the library.","o":["can","must","may","need"],"a":2,"e":"may have done表示对已发生事情的推测，可能性不确定。must have done表示非常确定，但语境不够确定，用may更合适。"},
{"id":307,"t":"choice","q":"You ___ have told me earlier. I could have helped you.","o":["should","can","may","must"],"a":0,"e":"should have done表示'本应该做某事（但没做）'，带有责备语气，'你本应该早点告诉我'。"},
{"id":308,"t":"choice","q":"He ___ be at home. The door is locked and the lights are off.","o":["must","can't","may","might"],"a":1,"e":"can't表示有把握的否定推测，'门锁着灯灭了，他不可能在家'。must不用于否定推测。"},
{"id":309,"t":"choice","q":"You ___ worry about him. He will be fine.","o":["can't","mustn't","needn't","shouldn't"],"a":2,"e":"needn't表示'没有必要'，'你不必担心他，他会没事的'。shouldn't侧重'不应该'，语义稍有偏差。"},
{"id":310,"t":"choice","q":"Even a child ___ know the answer to this question.","o":["can","may","must","need"],"a":0,"e":"can表示能力，'甚至一个孩子都能回答这个问题'。这里强调能力而非推测。"},
{"id":311,"t":"choice","q":"It ___ rain tomorrow. You'd better take an umbrella.","o":["must","need","may","can"],"a":2,"e":"may表示可能性推测，'明天可能会下雨'。must表示必然，太绝对；can一般不用于肯定推测。"},
{"id":312,"t":"choice","q":"He ___ have arrived by now. Let's call him.","o":["must","can","may","need"],"a":0,"e":"must have done表示对过去事情的肯定推测，'他现在应该已经到了'。by now暗示对现在状态的推测。"},
{"id":313,"t":"choice","q":"You ___ finish the work today, or the boss will be angry.","o":["need","must","can","may"],"a":1,"e":"must表示必须，'你今天必须完成工作'。need作为情态动词多用于否定句。"},
{"id":314,"t":"choice","q":"She ___ not have seen me, or she would have said hello.","o":["can","must","may","should"],"a":0,"e":"can't have done表示对过去事情的否定推测，'她不可能看到我，否则她会打招呼的'。"},
{"id":315,"t":"choice","q":"— Must I hand in my homework today? — No, you ___.","o":["mustn't","can't","needn't","won't"],"a":2,"e":"Must I...?的否定回答用needn't/don't have to，表示'不必'。mustn't表示禁止，语境不对。"},
{"id":316,"t":"choice","q":"He ___ drive, but he doesn't have a car now.","o":["can","could","may","must"],"a":0,"e":"can表示现在的能力'他会开车'，but后说明现在的状况。could表示过去的能力，与doesn't now不搭配。"},
{"id":317,"t":"choice","q":"You ___ not play with fire. It's dangerous.","o":["need","can","must","may"],"a":2,"e":"must not表示强烈禁止，'你绝对不能玩火'。语气比can't更强。"},
{"id":318,"t":"choice","q":"If you ___ help me, I would appreciate it.","o":["should","could","would","can"],"a":1,"e":"could表示委婉的请求，'如果你能帮我，我会很感激'。比can更礼貌。"},
{"id":319,"t":"choice","q":"The ground is wet. It ___ have rained last night.","o":["can","must","may","need"],"a":1,"e":"must have done表示对过去事情的肯定推测，地上湿了，昨晚一定下雨了。"},
{"id":320,"t":"choice","q":"You ___ tell anyone about this. It's a secret.","o":["mustn't","needn't","won't","couldn't"],"a":0,"e":"mustn't表示禁止，'你绝不能告诉任何人，这是个秘密'。"},
{"id":321,"t":"choice","q":"She ___ be in the office. I'm not sure.","o":["can","must","might","will"],"a":2,"e":"might表示可能性较小的推测，'她可能在办公室，我不确定'。比may可能性更小。"},
{"id":322,"t":"choice","q":"You ___ have been more careful. You made so many mistakes.","o":["should","can","may","must"],"a":0,"e":"should have done表示本应该做但没做，'你本应该更仔细些，你犯了这么多错'。"},
{"id":323,"t":"choice","q":"___ you please pass me the salt?","o":["Must","Need","Could","Will"],"a":2,"e":"Could you please...? 表示委婉的请求，'你能把盐递给我吗？'比can更礼貌。"},
{"id":324,"t":"choice","q":"He ___ have gone to Shanghai, but I'm not certain.","o":["must","can","may","should"],"a":2,"e":"may have done表示对过去事情不太确定的推测，'他可能去了上海'。I'm not certain是提示。"},
{"id":325,"t":"choice","q":"You ___ return the book before Friday.","o":["need","may","must","can"],"a":2,"e":"must表示义务和必要，'你必须在周五前还书'。"},
{"id":326,"t":"choice","q":"He ___ not have slept well last night. She looks tired.","o":["must","can","may","need"],"a":0,"e":"must have done（否定形式）表示肯定推测，'她昨晚一定没睡好'。She looks tired是推断依据。"},
{"id":327,"t":"choice","q":"We ___ to go to school on foot when we were young.","o":["should","must","had","used"],"a":3,"e":"used to do表示过去常常做某事（现在已经不做了），'我们小时候常常步行上学'。had to表示不得不，语境不符。"},
{"id":328,"t":"choice","q":"He ___ be sleeping. The light in his room is off.","o":["can","must","may","need"],"a":1,"e":"must be doing表示对现在正在发生的事的肯定推测，'他一定在睡觉'。灯灭了是推断依据。"},
{"id":329,"t":"choice","q":"You ___ eat too much junk food. It's bad for your health.","o":["shouldn't","needn't","mustn't","can't"],"a":0,"e":"shouldn't表示不应该，给出建议或忠告'你不应该吃太多垃圾食品'。mustn't语气太强（绝对禁止）。"},
{"id":330,"t":"choice","q":"He ___ have finished the work, for he is still working on it.","o":["can't","mustn't","needn't","won't"],"a":0,"e":"can't have done表示对过去事情的否定推测，'他不可能已经完成工作了，因为他还在做'。for表示原因。"},
{"id":331,"t":"choice","q":"I ___ like to have a cup of coffee.","o":["could","should","would","can"],"a":2,"e":"would like to do表示想要做某事，'我想要一杯咖啡'。是固定搭配。"},
{"id":332,"t":"choice","q":"You ___ bring your textbook to class every day.","o":["ought","need","should","shall"],"a":2,"e":"should表示应该，'你每天应该带课本来上课'。ought to也是正确但选项里是ought缺少to。"},
{"id":333,"t":"choice","q":"She ___ have left her keys at home. She can't find them anywhere.","o":["must","can","may","should"],"a":0,"e":"must have done表示肯定推测，'她一定把钥匙忘在家里了'。她到处都找不到是推断依据。"},
{"id":334,"t":"choice","q":"He ___ play the piano very well when he was five.","o":["can","could","may","must"],"a":1,"e":"could是can的过去式，'他五岁时就能弹钢琴弹得很好'。when he was five提示用过去式。"},
{"id":335,"t":"choice","q":"You ___ park here. It's not allowed.","o":["needn't","couldn't","mustn't","won't"],"a":2,"e":"mustn't表示禁止，'你不能在这里停车，这里不允许'。It's not allowed是禁止的提示。"},
{"id":336,"t":"choice","q":"If he ___ come tomorrow, I would let you know.","o":["will","should","can","may"],"a":1,"e":"if引导的条件句中，用should表示可能性较小的假设，'如果他明天来的话'。比may更正式。"},
{"id":337,"t":"choice","q":"He ___ not have received my letter, or he would have replied.","o":["can","must","should","may"],"a":0,"e":"can't have done表示否定推测，'他不可能收到我的信了，否则他会回复的'。or otherwise提示推断。"},
{"id":338,"t":"choice","q":"___ I borrow your pen for a moment?","o":["Must","Will","Shall","May"],"a":3,"e":"May I...? 请求许可的固定用法，'我可以借用你的笔吗？'"},
{"id":339,"t":"choice","q":"You ___ be tired after such a long journey.","o":["can","must","need","may"],"a":1,"e":"must表示有把握的推测，'经过这么长的旅途你一定很累'。有充分理由的推测用must。"},
{"id":340,"t":"choice","q":"He ___ go to work by bus, but now he drives his own car.","o":["used to","is used to","was used to","uses to"],"a":0,"e":"used to do表示过去常常做某事（现已不如此），'他过去常坐公交上班，现在开自己的车了'。be used to doing表示习惯于。"},
{"id":341,"t":"choice","q":"The man ___ is standing there is my father.","o":["who","which","whom","whose"],"a":0,"e":"先行词是man（人），在从句中作主语，用who。which只能指物。"},
{"id":342,"t":"choice","q":"This is the book ___ I bought yesterday.","o":["who","which","what","whom"],"a":1,"e":"先行词是book（物），在从句中作bought的宾语，用which/that。what不引导定语从句。"},
{"id":343,"t":"choice","q":"The girl ___ mother is a doctor studies very hard.","o":["who","whom","whose","which"],"a":2,"e":"whose引导定语从句表示'……的'，修饰girl，'那个妈妈是医生的女孩学习很努力'。whose可指人也可指物。"},
{"id":344,"t":"choice","q":"I'll never forget the day ___ I first came to this school.","o":["which","that","when","where"],"a":2,"e":"先行词是day（时间），在从句中作时间状语，用when。when = on which。"},
{"id":345,"t":"choice","q":"This is the place ___ we met for the first time.","o":["which","that","when","where"],"a":3,"e":"先行词是place（地点），在从句中作地点状语，用where。where = at which。"},
{"id":346,"t":"choice","q":"The reason ___ he was late was that he missed the bus.","o":["which","why","when","what"],"a":1,"e":"先行词是reason，在从句中作原因状语，用why。why = for which。"},
{"id":347,"t":"choice","q":"The students ___ don't study hard will not pass the exam.","o":["which","who","whom","whose"],"a":1,"e":"先行词是students（人），在从句中作主语，用who。which只能指物。"},
{"id":348,"t":"choice","q":"Is there anything ___ I can do for you?","o":["which","who","that","what"],"a":2,"e":"先行词是不定代词anything时，只能用that引导定语从句，不能用which。"},
{"id":349,"t":"choice","q":"This is the best film ___ I have ever seen.","o":["which","that","who","what"],"a":1,"e":"先行词被最高级best修饰时，只能用that引导定语从句，不能用which。"},
{"id":350,"t":"choice","q":"The house ___ roof is red belongs to my uncle.","o":["which","whose","that","of which"],"a":1,"e":"whose引导定语从句，表示'……的'，修饰house，'屋顶是红色的那栋房子属于我叔叔'。whose可以指物。"},
{"id":351,"t":"choice","q":"I know the man ___ you are talking about.","o":["which","whom","whose","where"],"a":1,"e":"先行词是man（人），在从句中作介词about的宾语，用whom。口语中也可用who/that。"},
{"id":352,"t":"choice","q":"The factory ___ my father works is very large.","o":["which","that","where","what"],"a":2,"e":"先行词是factory（地点），在从句中作works的地点状语，用where。where = in which。"},
{"id":353,"t":"choice","q":"She is the only person ___ understands me.","o":["which","who","that","whom"],"a":2,"e":"先行词被only修饰时，只能用that引导定语从句。虽然who语法上也对，但高考中only修饰时优先that。"},
{"id":354,"t":"choice","q":"I still remember the summer ___ we spent together.","o":["which","when","where","why"],"a":0,"e":"先行词是summer，但在从句中作spent的宾语（spent是及物动词），所以用which/that，不用when。when只能作状语。"},
{"id":355,"t":"choice","q":"I still remember the summer ___ we worked together.","o":["which","that","when","what"],"a":2,"e":"先行词是summer，在从句中作worked的时间状语（worked是不及物动词），用when。when = in which。"},
{"id":356,"t":"choice","q":"The woman ___ spoke to me just now is our teacher.","o":["which","who","whom","whose"],"a":1,"e":"先行词是woman（人），在从句中作spoke的主语，用who。whom只能作宾语。"},
{"id":357,"t":"choice","q":"He lives in a room ___ window faces south.","o":["which","that","whose","where"],"a":2,"e":"whose引导定语从句表示所属关系，'窗户朝南的房间'。whose可指物，相当于of which。"},
{"id":358,"t":"choice","q":"I'll never forget the days ___ we spent in the countryside.","o":["which","when","where","on which"],"a":0,"e":"先行词是days，但在从句中作spent的宾语，用which/that。spent是及物动词，不需要状语，所以不用when。"},
{"id":359,"t":"choice","q":"The professor ___ you want to see has gone abroad.","o":["which","whom","whose","where"],"a":1,"e":"先行词是professor（人），在从句中作see的宾语，用whom/who/that。whose表示'……的'，语义不符。"},
{"id":360,"t":"choice","q":"This is the school ___ I studied for three years.","o":["which","that","where","when"],"a":2,"e":"先行词是school（地点），在从句中作studied的地点状语，用where。where = at which。"},
{"id":361,"t":"choice","q":"Do you know the boy ___ father is a famous scientist?","o":["who","whom","whose","which"],"a":2,"e":"whose表示'……的'，修饰boy，'那个父亲是著名科学家的男孩'。whose在从句中作定语。"},
{"id":362,"t":"choice","q":"The book ___ cover is blue is mine.","o":["which","whose","of which","that"],"a":1,"e":"whose表示'……的'，可指物，'封面是蓝色的那本书是我的'。of which需要加the，如the cover of which。"},
{"id":363,"t":"choice","q":"He told me everything ___ he knew about the accident.","o":["which","that","who","what"],"a":1,"e":"先行词是不定代词everything时，只能用that引导定语从句，不能用which。"},
{"id":364,"t":"choice","q":"The first thing ___ I should do is to finish my homework.","o":["which","that","who","what"],"a":1,"e":"先行词被序数词first修饰时，只能用that引导定语从句，不能用which。"},
{"id":365,"t":"choice","q":"Is this the reason ___ he gave for being late?","o":["why","which","that","what"],"a":1,"e":"先行词是reason，但在从句中作gave的宾语（give sb. a reason），用which/that。why只能作状语。"},
{"id":366,"t":"choice","q":"The way ___ he solved the problem was very clever.","o":["which","that","in which","how"],"a":2,"e":"先行词是way时，用in which/that/不填来引导定语从句。不能用how，因为how=the way in which，会重复。"},
{"id":367,"t":"choice","q":"She has two sons, both of ___ are doctors.","o":["them","which","whom","who"],"a":2,"e":"介词后面指人用whom，both of whom是固定用法。them不能引导从句。"},
{"id":368,"t":"choice","q":"I bought a book, the cover of ___ is very beautiful.","o":["which","that","whose","what"],"a":0,"e":"介词of后面只能用which（指物），不能that。the cover of which = whose cover。"},
{"id":369,"t":"choice","q":"The hotel ___ we stayed during the holiday was excellent.","o":["which","that","where","when"],"a":2,"e":"先行词是hotel（地点），在从句中作stayed的地点状语，用where。where = at which。"},
{"id":370,"t":"choice","q":"Anyone ___ breaks the law will be punished.","o":["which","who","whom","whose"],"a":1,"e":"先行词是anyone（人），在从句中作breaks的主语，用who/that。whom只能作宾语。"},
{"id":371,"t":"choice","q":"He is such a good teacher ___ we all respect.","o":["which","who","as","whom"],"a":2,"e":"such...as是固定搭配，as引导定语从句，在从句中作宾语。as可以指人或物。"},
{"id":372,"t":"choice","q":"There is a table in the room, on ___ there are some books.","o":["which","that","whose","it"],"a":0,"e":"介词后面只能用which，不能用that。on which = where。"},
{"id":373,"t":"choice","q":"This is the same pen ___ I lost yesterday.","o":["which","that","as","who"],"a":2,"e":"the same...as是固定搭配，as引导定语从句，表示'和……一样的'。that表示同一个，但same通常配as。"},
{"id":374,"t":"choice","q":"We visited the house ___ Lu Xun once lived.","o":["which","that","where","when"],"a":2,"e":"先行词是house（地点），在从句中作lived的地点状语，用where。lived是不及物动词。"},
{"id":375,"t":"choice","q":"I have a friend ___ father is a lawyer.","o":["who","whom","whose","which"],"a":2,"e":"whose表示'……的'，修饰friend，'那个父亲是律师的朋友'。whose在从句中作定语修饰father。"},
{"id":376,"t":"choice","q":"The moment ___ I saw her, I fell in love with her.","o":["which","when","that","where"],"a":1,"e":"the moment作先行词表示时间，用when引导定语从句，作时间状语。the moment when... = the moment (that)..."},
{"id":377,"t":"choice","q":"The boy to ___ I lent my bike hasn't returned it yet.","o":["who","whom","whose","which"],"a":1,"e":"介词to后面指人用whom，to whom = to the boy。who不能直接放在介词后。"},
{"id":378,"t":"choice","q":"I don't like the way ___ he speaks to his mother.","o":["which","that","不填","how"],"a":2,"e":"先行词是way时，定语从句的引导词可以用that/in which/不填。不能用how，因为that已经包含了in which的含义。"},
{"id":379,"t":"choice","q":"All ___ can be done has been done.","o":["which","that","what","who"],"a":1,"e":"先行词是all（不定代词）时，只能用that引导定语从句，不能用which。what不引导定语从句。"},
{"id":380,"t":"choice","q":"The city ___ we visited last year is very beautiful.","o":["which","where","when","how"],"a":0,"e":"先行词是city，但在从句中作visited的宾语（及物动词），用which/that。不用where，因为visited不是不及物动词。"},
];
